### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by wbhob** [CaliStyle/angular2-intercom#1]
I think this is an NPM worthy package... would you consider publishing it?

**Comment by scott-wyatt** [comment]
@wbhob I haven't actually published a typescript package to npm before, do you have some advice on that?

**Comment by wbhob** [comment]
You should just be able to build it and upload. You'll need to create a package.json with a peer dependency of angular, and then you should be good to go.

**Comment by scott-wyatt** [comment]
This may take a bit for me to get this right, but i've published it to npm as [ng-intercom](https://www.npmjs.com/package/ng-intercom). Totally open to PRs as I don't have a ton of time right now. The only requirement is that it work for angular universal.
