### ISSUE TITLE
The onUnreadCountChange delegates to Intercom's onHide event handler

### ISSUE THREAD

**Issue by gerardmendes** [CaliStyle/angular2-intercom#20]
Or at least, this is my interpretation of [l193](https://github.com/CaliStyle/angular2-intercom/blob/master/src/intercom/intercom.ts#L193)

**Comment by wbhob** [comment]
Oh you're right, my oversite. I'll fix it and release in a few

**Comment by wbhob** [comment]
Fixed in beta 6
