### ISSUE TITLE
Error initialising Intercom in app.module.ts

### ISSUE THREAD

**Issue by newPrimitives** [CaliStyle/angular2-intercom#22]
I've installed Intercom through` npm install ng-intercom@beta --save `

When trying to import the Intercom in app.module.ts 

```
import { IntercomModule } from 'ng-intercom';
..
    IntercomModule.forRoot({
      appId: "your_app_id", 
      updateOnRouterChange: trueDefault: `false`
    })
..
```

I get the following two errors: 

```
Argument of type '{ appId: string; updateOnRouterChange: boolean; }' is not assignable to parameter of type 'IntercomConfig'.
Object literal may only specify known properties, and 'appId' does not exist in type 'IntercomConfig'.
```

I'm using Angular 4.

**Comment by newPrimitives** [comment]
Okay, I've just went through some other issues reported here and I've made it work based on a code snipped from an unrelated topic. Two things:
It's not **"appID"** anymore it's **"app_id"** and once i remove **updateOnRouterChange** It works. I'm not sure if it's just a matter of readme update or a bug in the code.

So switching from this:
```
IntercomModule.forRoot({
    appId: "your_app_id", 
    updateOnRouterChange: trueDefault: `false`
})
```

To this:

```
IntercomModule.forRoot({ app_id: "your_app_id" }) 
```

**Comment by newPrimitives** [comment]
Okay, for some strange reason this now works, I've installed intercom again by using 
`npm install ng-intercom --save` and it works, however the chat icon is not showing up. I'm also using the code from the readme with one addition, which is user_id.

**Comment by wbhob** [comment]
The beta has been moved to the `latest` tag, so that has the latest version. The code from the readme should not take a `user_id` property in `forRoot()`, so that may be your issue. Are you getting any console logs or errors?

**Comment by newPrimitives** [comment]
I've used user_id in my component when I wanted to display the intercom chat widget. I used the exact same code as the example in readme and initially i get **Intercom.init is deprecated and will be removed in a future release. Please use Intercom.boot.** After I replace to t**his.intercom.boot** nothing happens. No errors in the console. not widget in the corner.

**Comment by wbhob** [comment]
To clarify: `init` works, and `boot` does not?

**Comment by newPrimitives** [comment]
No, nothing works, the only difference is that init throws console warning and boot doesn't show anything. In both cases, I don't see the chat widget in the corner. Just to test it, I've included a vanilla JS code in my index.html file in the header and the chat button shows up, so it's definitely an issue with the library.

**Comment by wbhob** [comment]
@newPrimitives `init` is deprecated in favor of `boot` to more closely match the IntercomJS API.

Can you please share a repo so I can see the issue?

**Comment by newPrimitives** [comment]
It's a private repo but here's how I integrate it in the component:

In the app.module.ts

```
...

import { IntercomModule } from 'ng-intercom';

@NgModule({
  declarations: [
    ...
  ],
  imports: [
    ....
    IntercomModule.forRoot({ appId: "XXXX", updateOnRouterChange: true })
  ],
})

```

In the component:

```
....

import { Intercom } from 'ng-intercom';

...

export class ManageSpacesComponent implements OnInit {

constructor(private router: Router, private db: AngularFireDatabase, private auth: AuthService, public intercom: Intercom) {
 
  }

ngOnInit() {
    this.intercom.boot({
      app_id: "XXXXX",
      widget: {
        "activator": "#intercom" 
      }
    });
  }
}
```

For the sake of testing I just want to see a blue chat bubble in the bottom right corner.

**Comment by wbhob** [comment]
just call `this.intercom.boot`, and `appId` should be `app_id`

**Comment by wbhob** [comment]
If that is the issue, let me know so I can fix the docs

**Comment by newPrimitives** [comment]
Unfortunately, not. My IntercomConfig looks like this:

```
export interface IntercomConfig {
    appId: string;
    updateOnRouterChange?: boolean;
    apiToken?: string;
}
```

so **app_id** instead of **appId** throws an error. Calling just **this.intercom.boot()** doesn't help either.

**Comment by wbhob** [comment]
What version are you on?

**Comment by newPrimitives** [comment]
npm-list shows ng-intercom@1.0.0-beta.6

**Comment by wbhob** [comment]
Ok I’ll try to take a look tonight. Thanks for letting us know!

**Comment by newPrimitives** [comment]
Thank you, let me know the results, really appreciate it.

**Comment by alexnoox** [comment]
I'm having the same issue. I've been investigating a bit:
- To display the default button, the correct `boot` config option is **#IntercomDefaultWidget**:
```
widget: {
  activator: "#IntercomDefaultWidget"
}
```

- `IntercomModule.forRoot({appId: environment.intercom.app_id}),` seems to be the right syntax `appId` is only used to initialise Intercom JS code (cf. https://github.com/CaliStyle/angular2-intercom/blob/master/src/intercom/intercom.ts#L19)

The only issue that I encounter now is that I can't use `alignment: 'left'`. It is working when using the vanilla JS, but not using the lib.

**Comment by wbhob** [comment]
I'm beginning to think it's something wrong with loading intercom asynchronously. I may need to dive in and investigate more. PRs would be accepted and greatly appreciated

**Comment by wbhob** [comment]
Update: I can reproduce this error. It seems to be a whitelist error, but it could be something entirely different. Open to suggestions and PRs.

**Comment by wbhob** [comment]
Alright folks, I just released beta.7. Thanks for your patience! I've verified that it is working locally.

As an aside, make sure that you have whitelisted `localhost` so that Intercom knows requests are coming from you. I recommend using the TEST app so that you don't go into production with localhost whitelisted!
