### ISSUE TITLE
Getting issues when installing this module for angular cli project

### ISSUE THREAD

**Issue by rajesh-mobicules** [CaliStyle/angular2-intercom#25]
Hi,

I am getting error Metadata version mismatch for module ../node_modules/ng-intercom/dist/index.d.ts, found version 4, expected 3,

I am using angular cli. The angular cli version is up to date!.

Please suggest.

**Comment by wbhob** [comment]
Is your Angular version v5 or higher?

**Comment by rajesh-mobicules** [comment]
My angular version is angular 4.

**Comment by wbhob** [comment]
That's the reason. Upgrade to Angular v5 and the issue will go away.

**Comment by rajesh-mobicules** [comment]
I upgraded angular core, angular common to version 5 but getting the same issue!

**Comment by wbhob** [comment]
Everything needs to be v5.

`rm -r node_modules; rm package-lock.json; npm install`

**Comment by wbhob** [comment]
Closing due to no response.
