### ISSUE TITLE
add vertical_padding: options

### ISSUE THREAD

**Issue by Lionardo** [CaliStyle/angular2-intercom#26]
I don't see any possibility on how I can change the vertical padding for my intercom chat. In the docs of intercom they suggest to use this method. Is there a possibility to do this?
Cheers

```
window.intercomSettings = {
    app_id: ‘abc123’,
    alignment: 'left',			# Customize left or right position of messenger
    horizontal_padding: 20,		# Customize horizontal padding
    vertical_padding: 20		# Customize vertical padding
  };
```

**Comment by wbhob** [comment]
That's something I can add. Can you link to docs please?

**Comment by Lionardo** [comment]
cool. here are the docs:
https://developers.intercom.com/docs/configuration

**Comment by wbhob** [comment]
Alrighty, added these features in beta 11
