### ISSUE TITLE
How to use app_id returned from API

### ISSUE THREAD

**Issue by hassanasad** [CaliStyle/angular2-intercom#28]
Is it possible to provide the {app_id} for intercom at a later stage? I have to pull that using an API call so its not available at boot time.

For that reason i dont have app_id to put here:
```
IntercomModule.forRoot({
      appId: <your_app_id>, // from your Intercom config
})
```

**Comment by wbhob** [comment]
Currently, this is synchronous, so it can be statically analyzed by the compiler. If you have another suggestion of how to implement it, I'd be open to a PR.

**Comment by hassanasad** [comment]
How about we make the `appId` optional in the `.forRoot` method and instead pick it up from `Intercom.boot({config})`? Can that work?

**Comment by hassanasad** [comment]
@wbhob Would it be possible that way ?

**Comment by wbhob** [comment]
Actually I realized that even Intercom's regular code requires you to pass in an ID to the loading script. I can't think of a good way to do this. I don't really understand why you'd load the ID from the server, though. Even if someone does get your ID, you can just whitelist your app's domain and they can't get in.

**Comment by hassanasad** [comment]
@wbhob Thanks for looking into this.

I was wondering if we use the `loadIntercom` function when you call `intercom.boot()` method. Wont that work?

The benefit of getting `appId` from API is that you do not need to hardcode it in your client side app. (I know that you can set it in environment and then use its build but if we can somehow capture it later in program life-cycle, it would be much more beneficial)

**Comment by wbhob** [comment]
So you mean, defer loadIntercom until you (the consumer) calls it?

**Comment by wbhob** [comment]
It's just that the config in forRoot doesn't just loadIntercom, but it is used by the Intercom provider and the directives to function properly, which is why it's hard to go outside of the module context. The way I have it in my apps is I just use environment variables. It's the fastest, most statically-analyzable way.

**Comment by hassanasad** [comment]
Yes. Call loadIntercom when user calls the intercom.boot method.
Just a suggestion though.

**Comment by hassanasad** [comment]
Perhaps in that case you bind a dummy Intercom object to window and on boot
fire an event to trigger and essential stuff you do on loadintercom.

**Comment by hassanasad** [comment]
I know you want this too if you think it's possible to do. I read in a blog
post for the inspiration behind this package 😊

**Comment by wbhob** [comment]
I'd be open to seeing a PR for this, but unfortunately, I don't really have time for this functionality. This seems like a pretty edge use case for simply hardcoding it in, which is the way everyone uses Intercom. 

If you have multiple apps, you can check out this fork of our project: https://www.npmjs.com/package/ng-intercom-multi

**Comment by wbhob** [comment]
This is available in the Intercom.id property. Closing
