### ISSUE TITLE
Attach a method or service on route change

### ISSUE THREAD

**Issue by hassanasad** [CaliStyle/angular2-intercom#29]
Is it possible to attach a method to be called from service on each route change?

For example, 
If i setup:
```
IntercomModule.forRoot({
      updateOnRouterChange: true
})
```

Can i bind a function to be called on each route change to manipulate intercom data to be sent?

**Comment by wbhob** [comment]
Yes, but this is not the place to ask.

This can help: https://stackoverflow.com/questions/42453375/how-to-call-a-function-on-every-rotute-change-in-angular2

**Comment by hassanasad** [comment]
Its related to intercom. I am trying to fetch some properties from API to
be pushed as intercom data on each route change.
Anyways, thanks for the link
