### ISSUE TITLE
Version Mismatch

### ISSUE THREAD

**Issue by felipegomesflg** [CaliStyle/angular2-intercom#30]
I could use it for dev with no problems, but when i build for prod i had this error comming up:

`ERROR in Metadata version mismatch for module C:/mdc/mdc.pagalee.dashboard/node_modules/ng-intercom/dist/index.d.ts, found version 4, expected 3, resolving symbol AppModule in C:/mdc/mdc.pagalee.dashboard/src/app/app.module.ts, resolving symbol AppModule in C:/mdc/mdc.pagalee.dashboard/src/app/app.module.ts, resolving symbol AppModule in C:/mdc/mdc.pagalee.dashboard/src/app/app.module.ts`

I'm running this application on angular5

**Comment by wbhob** [comment]
Nuke node_modules and npm install, that should fix your issue.

**Comment by felipegomesflg** [comment]
My angular 5 packages was on beta, put it all on rc and worked just fine. Thanks anyways!

**Comment by wbhob** [comment]
Angular 5 is extremely stable, you can use 5.2 now if you like and it will work
