### ISSUE TITLE
Beta.11 intercom no longer opens/loads

### ISSUE THREAD

**Issue by matt-filion** [CaliStyle/angular2-intercom#32]
It does not appear to be calling the l() function within the util/load-intercom.ts file anymore.

**Comment by wbhob** [comment]
Do you have any other information? Errors in the console, or something that would lead you to believe that that is the case? The code has not changed for that function, and it is ported directly from Intercom.

**Comment by matt-filion** [comment]
When I changed back to .10 it worked. I'll dig a bit deeper to see what I
can find. In the latest version I could not place what is calling the l()
function. Do you know what is "supposed" to be invoking it?

**Comment by wbhob** [comment]
window.onLoad should be invoking it in compatible browsers, if not, it adds an eventlistener for load.

**Comment by MarkusPint** [comment]
I can confirm this. It happens on beta.12 too and switching back to beta.10 fixes it. There are no errors in console.

**Comment by worldspawn** [comment]
I'm using beta11 on one site without issue and on another using beta11 the load event has fired at the time the intercom runs `loadIntercom`. Nfi why, it's all initialised in the same way. Only thought I had it something to do with how the modules were bundled (for lazy loading).

Could we perhaps do something like:

``` js
else {
  if (w.document.readyState === 'complete')
     l();
  else {
     w.addEventListener('load', l, false);
  }
}
```

Though when i try that i get this in my log output
![image](https://user-images.githubusercontent.com/819581/38292859-abe3c27c-3828-11e8-9fc1-06b3714be708.png)

**Comment by sijmenvos** [comment]
I can also confirm this, when using 1.0.0-beta.10 Intercom loads, on 1.0.0-beta.13 it doesn't either.

**Comment by scott-wyatt** [comment]
Marking this as a deprecated issue. Feel free to reopen another issue if this persists in a later version.
