### ISSUE TITLE
Property 'init' does not exist on type 'Intercom'

### ISSUE THREAD

**Issue by epoxy** [CaliStyle/angular2-intercom#33]
In the readme regarding ngOnInit() it says that the following line should be used:

> this.intercom.init({

This gives me the error:

> Property 'init' does not exist on type 'Intercom'

This error only occurred for version 1.0.0-beta.11 and not for 1.0.0-beta.10. I managed to fix it by using update instead of init. Perhaps the line in the readme should be changed to:

> this.intercom.update({

**Comment by wbhob** [comment]
`init` is not actually an Intercom method anymore. Use `boot` to match the official intercom docs.
