### ISSUE TITLE
Rename Repo to "ng-intercom" to match the npm package

### ISSUE THREAD

**Issue by scott-wyatt** [CaliStyle/angular2-intercom#36]
@wbhob, I would like your feedback on this.

**Comment by wbhob** [comment]
I agree. We’ll need to coordinate this change with the next npm release so the links are accurate

**Comment by scott-wyatt** [comment]
Cool, good news is, as long we don't reuse the `angular2-intercom` namespace in this organization, github will just redirect requests to the new name.

**Comment by wbhob** [comment]
Sounds good. ready when you are

**Comment by scott-wyatt** [comment]
Renamed! Cheers
