### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Srilatha50** [CaliStyle/angular2-intercom#41]
I'm getting the following error when I tried installing ng-intercom using yarn

**error ng-intercom@1.0.0-beta.12: Expected version ">= 6.0.0 < 7.0.0.** 

Before you submit an issue, please include:

- [ ] Angular Version: 4
- [ ] Angular CLI Version: 1.2.6
- [ ] Node & NPM Version: 9.5.0 & 5.6.0 respectively

Detailed Description on how to reproduce error:
yarn add ng-intercom or yarn add ng-intercom@latest

**Comment by Senthilkumar-Fullstack** [comment]
Myself too face the same issue.
I'm using Windows 7 OS.
Please anyone help me to resolve the issue.

The same installation command is working fine for Linux and Mac OS.

**Comment by scott-wyatt** [comment]
Fixed by #42
