### ISSUE TITLE
Undefined from http request 

### ISSUE THREAD

**Issue by BCusack** [CaliStyle/angular2-intercom#44]
Bug

Angular Version = 5.2.1
Angular CLI Version = 1.7.4
Node & NPM Version = 5.8.0

When loading the app at localhost and booting intercom widget, http request returns **undifind** from the request to 'https://widget.intercom.io/widget/undifined'.
I've traced this back to **ng-intercom.js** at:

`   Intercom.prototype.l = function () {
        var d = document;
        var s = d.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = "https://widget.intercom.io/widget/" + this.id;
        var x = d.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    };`

 as **this.id** is not a known variable of the function call **this.l** it returns **undifined** and should be:

`   Intercom.prototype.l = function (config) {
        var d = document;
        this.id = config.appId;
        var s = d.createElement('script');
        s.type = 'text/javascript';
        s.async = true;
        s.src = "https://widget.intercom.io/widget/" + this.id;
        var x = d.getElementsByTagName('script')[0];
        x.parentNode.insertBefore(s, x);
    };`, 

than used as 'this.l(config);'

**Comment by scott-wyatt** [comment]
Can you show your CLI and tsconfig?

**Comment by BCusack** [comment]
![tsconfig](https://user-images.githubusercontent.com/10039059/39402361-850a1d96-4ba0-11e8-8e60-7e3cb327c0d3.JPG)
![cli](https://user-images.githubusercontent.com/10039059/39402362-8dd573bc-4ba0-11e8-9ded-3b33b1c6db22.JPG)

**Comment by wbhob** [comment]
Have you tested this with v6?

**Comment by wbhob** [comment]
Closing due to no response. If this issue persists, please open a new issue.

**Comment by BCusack** [comment]
I’ll be spinning up a new project with v6, but intercom integration wants be until September. Let you know. Thanks
