### ISSUE TITLE
Replacing API keys with Access Tokens

### ISSUE THREAD

**Issue by Svrkota-S** [CaliStyle/angular2-intercom#45]
Hi, is `ng-intercom` going to publish an update in order to support latest update with Access Tokens? You can read about it here: https://developers.intercom.com/v2.0/docs/replacing-your-api-keys-with-access-tokens-step-by-step-guide#section-step-2-replace-your-api-keys

I received an email which says:

> As you may be aware, we've been in the process of deprecating API Keys over the past 18 months in favour of more secure methods. As the final step of this process, your API Keys will be disabled at 4pm GMT on April 23 2018.

Thanks in advance for any reply!

**Comment by scott-wyatt** [comment]
Hi! We actually use the appId in ng-intercom, we don't use the api key at all.  With a client side application, you really don't want to expose your key or token, which is why intercom allows for the appId to drive the client side communication. Hope this helps, cheers!
