### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by Koslun** [CaliStyle/angular2-intercom#47]
- Angular Version 6.0.0
- Angular CLI Version 6.0.0
- RxJS Version 6.1.0
- TypeScript Version 2.7.2
- Node Version 8.9.1
- NPM Version 5.5.1
- **ng-intercom Version 1.0.0-beta.13**

**Expected/desired**
Support Angular 6, TypeScript 2.7 and RxJS 6 without errors

**Actual**
Getting this error when starting a newly created angular-cli project with this library added to it:
```
TypeError: Cannot read property 'events' of null
```

Here is the [project and branch ](https://github.com/Koslun/ng-example-app/tree/feat/ng6-intercom) reproducing the above error. Created the project using angular-cli defaults with yarn as the package manager while also adding rxjs-compat, which should smooth over being able to use  RxJS 5.x.

**Solution**
A large part of the work might be possible by simply using `ng update` with `@angular/core` and `rxjs` as outlined in the [Angular 6 release post](https://blog.angular.io/version-6-of-angular-now-available-cc56b0efa7a4).

Given that I think upgrading to support Angular 6 will invariably break everyone using below angular 5 and below I think it would make sense to couple this update with a major version bump. Meaning bumping the version number to 2.x.

**Comment by scott-wyatt** [comment]
I’d be very open to a PR, otherwise I’ll have to wait till this hits my deployment schedule for angular 6.

**Comment by Koslun** [comment]
@scott-wyatt ok, will see if I can get some time later this week to try out the automated tooling I mentioned to provide a PR.

Looking at the git commit log I presume it'll be fine to follow the [AngularJS git commit message conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit) or similar [Conventional Commits](https://conventionalcommits.org/)

**Comment by Koslun** [comment]
Have a WIP solution in PR #49. Missing some things that I don't think matter for consuming apps.

Noticed however that Angular itself maybe still worked as the above error was due to not including a router even though I used the router config of this library.
