### ISSUE TITLE
Sending custome values with intercom.update

### ISSUE THREAD

**Issue by kwiesmueller** [CaliStyle/angular2-intercom#55]
## Versions
- **Angular:** "^5.2.0",
- **ng-intercom:** "ng-intercom": "^6.0.0-beta.1",

## Description
When doing an intercom update call like this:
```
this.intercom.update({
      'foo': 'bar',
    });
```
The custom variable (defined in intercom) is not being set for the user.

**Comment by wbhob** [comment]
Angular needs to be v6 to work with ng-intercom v6. Also please share console logs and surrounding code.

**Comment by kwiesmueller** [comment]
Ah, stupid me...
That works! I even saw the table in the Readme but must have miexed up the lines.
Thanks!
