### ISSUE TITLE
Intercom js loaded on window.onload instead of scriptElement.onload

### ISSUE THREAD

**Issue by tiberiumihai** [CaliStyle/angular2-intercom#58]
## Versions

- **Angular:** 5.2.0
- **Angular CLI:** 1.6.8
- **ng-intercom:** 6.0.0-beta.2
- **Node.JS:** <none>
- **NPM:** 5.8.0

## Description
IntercomJS is loaded on window.onload event instead of scriptElement.onload, or by a function to init and load the js. 

When intercom js is injected before window.load is fired, the module will load and work just fine.
But when intercom is injected after window.load was fired, the intercom JS won't be loaded because window.load already fired, and thus the component won't work.

To fix this issue, we had to use this workaround in our wrapper component to manually load the intercom js.

```
const intercomJsNotLoaded = !$(`script[src="https://widget.intercom.io/widget/${environment.intercomKey}"]`).length;
if (intercomJsNotLoaded) {
  // Load Intercom JS
  const loadIntercomJS: any = this.intercom.l(this.intercomConfig);
  loadIntercomJS.apply(this.intercom);
}
```

## Possible solution
Is it possible to move the module loading through a function to be called manually or replace the `window.onload` with `scriptElement.onload` of the intercom js script injected?

**Comment by tienvx** [comment]
I confirm this is a bug. The workaround work like a charm.

**Comment by wbhob** [comment]
I'd definitely be open to seeing a PR for this issue. This seems like a simple enough fix, but currently the behavior lives inside the provider. I remember, it was formerly outside of the provider, and would execute before Angular's instantiation. I'd be open to seeing a new implementation of a fix for this issue, though. Thanks!

**Comment by tiberiumihai** [comment]
Sure. I'm working on a Fix, I'll send a PR when it's finished. Thanks!

**Comment by tiberiumihai** [comment]
I'm trying to push a new branch `fix-injecting-intercom-script` where the changes resides but I get this:

```
ERROR: Permission to CaliStyle/ng-intercom.git denied to tiberiumihai.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by scott-wyatt** [comment]
You’ll want to fork the repo and do a pull request. Thanks!

**Comment by tiberiumihai** [comment]
@wbhob @scott-wyatt I've added the PR with the fix. Can you take a look and let me know if it requires anything else? It seems that the bug is gone after this fix.

**Comment by tiberiumihai** [comment]
After merging and publishing to 6.0.0beta3, this issue is now fixed. Thanks!

Closing.
