### ISSUE TITLE
Angular 5 support?

### ISSUE THREAD

**Issue by kodeine** [CaliStyle/angular2-intercom#61]
Hello, 
Does it support angular 5?

**Comment by kodeine** [comment]
i am getting the following error.

<img width="577" alt="screen shot 2018-09-10 at 12 40 54 am" src="https://user-images.githubusercontent.com/8620059/45278337-3b6ca180-b492-11e8-957b-ef491716ad6f.png">

**Comment by wbhob** [comment]
Angular 5 support was dropped in favor of Angular 6. There are still betas tagged 5.0.0-beta.x that support angular 5, but those are no longer being supported.

This error you shared in particular is from Ionic. You don't have @angular/router installed, which causes this issue.
