### ISSUE TITLE
window.Intercom is not a function

### ISSUE THREAD

**Issue by hassanasad** [CaliStyle/angular2-intercom#62]
## Versions

- **Angular:** 6.1.6
- **Angular CLI:** 6.1.5
- **ng-intercom:** 6.0.0-beta.3
- **Node.JS:** 10.9.0
- **NPM:** 6.4.1

## Description
After moving to beta.3, started getting errors `Object doesn't support property or method 'Intercom'`

**File**
webpack:///node_modules/ng-intercom/esm5/ng-intercom.js:57e.prototype.update

Sometimes another error shows `window.Intercom is not a function`

**File**
webpack:///node_modules/ng-intercom/esm5/ng-intercom.js:58e.prototype.update

It was working fine with beta.2

Attached image from bugsnag for reference.
![screenshot 2018-09-12 13 15 29](https://user-images.githubusercontent.com/7580112/45411604-0af15700-b68e-11e8-8ba8-00a7c7607994.png)

**Comment by wbhob** [comment]
Can you share browser/os info please

**Comment by hassanasad** [comment]
I have checked and its not one specific OS or browser.

Its reported on:
- Chrome 68 on Windows 7
- Safari 1.1.2 on Mac OS X 10.13
- Edge 17.17134.0 on Windows 10

**Comment by hassanasad** [comment]
@wbhob any update ? :)

**Comment by wbhob** [comment]
Sorry, I have no idea what this issue might be. How is this being called? Have you verified that the Intercom JS has been loaded?

**Comment by hassanasad** [comment]
I couldn't stay on beta3 for long because of this issue. Reverting back to beta2 fixes the issue for me :)

**Comment by ghost** [comment]
Same here

**Comment by wbhob** [comment]
@scott-wyatt do you have any idea what the issue might be?

**Comment by ghost** [comment]
@wbhob race condition, I dunno. Just rolled-back to beta2.

**Comment by scott-wyatt** [comment]
Yeah, there really should be a test that Intercom is defined on the window before it attempts this, that's likely the issue.

**Comment by wbhob** [comment]
I attempted a fix in #67. Sorry for the lack of attention on our end!
