### ISSUE TITLE
showing for Angular 2+ wrapper version

### ISSUE THREAD

**Issue by shailendra-bhargava** [CaliStyle/angular2-intercom#64]
## Versions

- **Angular:** 
- **Angular CLI:** 
- **ng-intercom:** 
- **Node.JS:** 
- **NPM:** 

## Description

this error is coming while running ng build --prod

/node_modules/ng-intercom/ng-intercom.d.ts, found version 4, expected 3

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory'

**Comment by wbhob** [comment]
You have the wrong version of Angular. Next time, please *follow the issue template*.
