### ISSUE TITLE
TypeError: Cannot read property 'boot' of undefined

### ISSUE THREAD

**Issue by JohnnyTMD** [CaliStyle/angular2-intercom#65]
I have installed the module following the instructions and i get this error ”TypeError: Cannot read property 'boot' of undefined”. Here is the code:

`  public intercom: Intercom
  constructor() { 
  }

  ngOnInit() {
      this.intercom.boot({  /// <--- on this line is the error
        app_id: 'app-id',
        widget: {
          "activator": "#intercom"
        }
      });
  }`

**Comment by justinasit** [comment]
You should inject intercom provider into the component like this:
`constructor(private intercom: Intercom) {}`

**Comment by wbhob** [comment]
@justinasit is right. Injectable providers must go in constructor, not outside of it.
