### ISSUE TITLE
appId being ignored in boot method

### ISSUE THREAD

**Issue by Greatsamps** [CaliStyle/angular2-intercom#72]
## Versions

- **Angular: 6.0.0 
- **Angular CLI: 6.2.3
- **ng-intercom: 6.0.0 
- **Node.JS: 8.12.0 
- **NPM: 6.4.1 

## Description
I have followed the instruction in the main readme, which indicates that the intercom appId can be overridden via a boot method which is what we require. The project we are working on has multiple appId's, depending on the domain that's being accessed.

Unless an appId is specified in the forRoot method, the intercom messenger does not load. Based on the documentation it would seem that the appId can be replaced via the boot method, but this is not the case.

**Comment by wbhob** [comment]
I have an idea for what to do here @scott-wyatt I'll try to make a PR this evening

**Comment by Greatsamps** [comment]
I have managed to fix this, let me know if you are interested in the solution...

**Comment by wbhob** [comment]
@Greatsamps what is the solution?

**Comment by wbhob** [comment]
#72 addresses this issue
