### ISSUE TITLE
Event metadata must be an object

### ISSUE THREAD

**Issue by davcj** [CaliStyle/angular2-intercom#77]
## Versions

- **Angular:** 6.1.0
- **ng-intercom:** 6.0.0

## Description

I got error "Event metadata must be an object" when trying to call function trackEvent with metadata. Function   "public trackEvent(eventName: string, metadata?: string)" should accept metadata argument of type any, not string.

Thanks in advance

**Comment by wbhob** [comment]
fixed in #78
