### ISSUE TITLE
Function calls are not supported in decorators but 'IntercomModule' was called.

### ISSUE THREAD

**Issue by StevenH86** [CaliStyle/angular2-intercom#82]
I am getting this error when trying to build.

ERROR in Error during template compile of 'AppModule'
  Function calls are not supported in decorators but 'IntercomModule' was called.

Using Angular 6.1.1 with Ionic Framework 4.0.0-beta.7

Any ideas? Never had to fix an issue like this before.

**Comment by wbhob** [comment]
we are aware of this issue in #74
