### ISSUE TITLE
Please ensure your intercomSettings object is formatted correctly: Missing App ID.

### ISSUE THREAD

**Issue by eyalhakim** [CaliStyle/angular2-intercom#86]
## Versions

- **Angular:** 7.0.2
- **Angular CLI:** 7.0.4
- **ng-intercom:** 7.0.0-beta.1
- **Node.JS:** 10.1.0
- **NPM:** 6.7.0

## Description

A warning is thrown despite everything working correctly:
`Please ensure your intercomSettings object is formatted correctly: Missing App ID.`

I spoke to Intercom and they confirmed they do not see this error on their logs.

**Comment by alexyoungs** [comment]
I've also just started seeing this having had it working for a while.

**Comment by JohnnyTMD** [comment]
I've also just started seeing this and it appeared without touching any intercom related code.

**Comment by scott-wyatt** [comment]
@eyalhakim can you put the output from the console in the issue?

**Comment by scott-wyatt** [comment]
This appears to be a change from Intercom, nothing we can really do here until intercom publishes their updated documentation.

**Comment by eyalhakim** [comment]
@scott-wyatt here is the output:
`frame.b9364e05.js:1 Please ensure your intercomSettings object is formatted correctly: Missing App ID.

safeConsoleWarn @ frame.b9364e05.js:1

t.createOrUpdateUser @ frame.b9364e05.js:1

t.createOrUpdateUser @ frame.b9364e05.js:1

update @ frame.b9364e05.js:1

(anonymous) @ frame.b9364e05.js:1

processApiQueue @ frame.b9364e05.js:1

(anonymous) @ frame.b9364e05.js:1

p @ frame.b9364e05.js:1

(anonymous) @ frame.b9364e05.js:1

p @ frame.b9364e05.js:1

(anonymous) @ frame.b9364e05.js:1

p @ frame.b9364e05.js:1

m @ frame.b9364e05.js:1

(anonymous) @ frame.b9364e05.js:1

(anonymous) @ frame.b9364e05.js:1
`

**Comment by alexyoungs** [comment]
Solved this for now by removing ng-intercom, adding the intercom snippet to index.html and using the following in app.component:

`
(<any>window).Intercom(‘boot’, {
    app_id: ***
});
`

Further to this, I subscribed to the current logged in user as well as router events to handle page changes and sending user details, by calling the following:
`
(<any>window).Intercom('update', {
    email: 'email@here.com'
    ... etc
});
`

Shut down intercom by calling:

`
(<any>window).Intercom('shutdown');
`

Seems to work. 

I have wrapped this all in a service, but I hope this helps anyone in a similar situation whilst this module is being updated.

**Comment by danielhusar** [comment]
Sorry guys sorry for breaking this!
Simply adding `window.intercomSettings` with appId will remove the warning.

I will remove the warning meanwhile to avoid any false positives.

**Comment by scott-wyatt** [comment]
Thanks @danielhusar, we will add `window.intercomSettings` to the source and push as soon as possible.
