### ISSUE TITLE
Star tour function needed

### ISSUE THREAD

**Issue by eyalhakim** [CaliStyle/angular2-intercom#95]
## Versions

- **Angular:** 
- **Angular CLI:** 
- **ng-intercom:** 
- **Node.JS:** 
- **NPM:**

**Comment by wbhob** [comment]
Can you send a link to documentation please? I don't know what "start tour" is in Intercom.

**Comment by eyalhakim** [comment]
@wbhob It's the newest Intercom feature:
https://developers.intercom.com/installing-intercom/docs/intercom-javascript#section-intercomstarttour-tourid

**Comment by vgensw** [comment]
@wbhob could you please release your latest commits? Version 8.0.0.beta-1 is still the latest release (I guess) :-)

thank you!

**Comment by wbhob** [comment]
@scott-wyatt i updated the version but evidently it didn't deploy

**Comment by scott-wyatt** [comment]
Did you do a release?

**Comment by wbhob** [comment]
I `npm version`'d it and I thought it did it automatically. guess not

**Comment by scott-wyatt** [comment]
Yeah, you still have to create a github release with a v8.0.0<version>, that triggers the CI to publish to NPM.

**Comment by wbhob** [comment]
got it. its going now.
