### ISSUE TITLE
Route performance problems using updateOnRouterChange

### ISSUE THREAD

**Issue by andy-hook** [CaliStyle/angular2-intercom#97]
## Versions

- **Angular:** 8.2.8
- **Angular CLI:** 8.3.6
- **ng-intercom:** 8.0.0
- **Node.JS:** 10.11.0 
- **NPM:** 6.4.1

## Description

I'm experiencing significant performance problems when changing routes with updateOnRouterChange enabled. In my profiler some of my tasks takes up to 5 or 6 times as long.

Here's an example from clicking between two routes in my app:

`updateOnRouterChange: false`
![image](https://user-images.githubusercontent.com/11708259/72153519-236aa200-33a6-11ea-8884-b0a4ee34465e.png)

`updateOnRouterChange: true`
![image](https://user-images.githubusercontent.com/11708259/72153538-341b1800-33a6-11ea-9bfa-61d42947bcde.png)

Has anyone come up against these issues before?

**Comment by andy-hook** [comment]
I did some digging and the intercom update function is being called many times due to a subscription matching all router events. Changing this to match for NavigationEnd should fix the issue.

**Comment by andy-hook** [comment]
Hi @scott-wyatt @wbhob – Are you able to publish with this change?

**Comment by andy-hook** [comment]
@scott-wyatt, @wbhob – I hate to be that guy but what's the eta on getting 8.0.1 published to npm?

**Comment by scott-wyatt** [comment]
Opps! Sorry about that, I thought it published. I’ll publish it to npm this morning

**Comment by andy-hook** [comment]
Thanks for getting this out!  🎉
